version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    container_name: techtok-app
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - NODE_ENV=development
    ports:
      - "5173:5173"
      - "8080:8080"
    command: sleep infinity
    networks:
      - spring-network

  postgres:
    image: postgres:latest
    container_name: spring-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      timeout: 20s
      retries: 10
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge
